import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--철수의폰트변수",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--글로벌폰트변수",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// interface IProfile {
//   name: string
//   age: number
//   school: string
// }

interface IProps {
  children: React.ReactNode;
}
export default function RootLayout(props: IProps) {

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>===============여기 위는 레이아웃 입니다.===============</div>
        {props.children}
        <div>===============여기 아래는 레이아웃 입니다.===============</div>
      </body>
    </html>
  );
}
